[build]
    functions = "functions"
    publish = "dist"
    command = "gridsome build"

[build.environment]
  NODE_VERSION="16.16.0"

[dev]
  command = "gridsome develop" # Command to start your dev server
  targetPort = 8080 # The port for your application server, framework or site generator
  
